{{- if .Values.gateway.enabled -}}
{{- $fullName := include "docusaurus.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ $fullName }}
      kind: ListenerSet
      group: gateway.networking.k8s.io
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- end }}
