---
name: X
accessGroup1: ""
accessGroup2: ""
accessPrefix: "fhburgenland-bswe:swm2-ws2026-group-"

policies:
  enabled: true
  domain:
    exposed: student.bswe.hochschule-burgenland.muehlbachler.xyz
    registry: registry.hochschule-burgenland.muehlbachler.xyz
  imagePullSecret:
    name: registry-credentials
  signatures:
    enabled: false
    onlyNamed: true

repoURL: https://github.com/fhburgenland-bswe/swm2-ws2026-kubernetes-applications.git
