---
apiVersion: object.scaleway.m.upbound.io/v1alpha1
kind: Bucket
metadata:
  name: live
spec:
  forProvider:
    name: crossplane-bucket-live
    forceDestroy: true
  providerConfigRef:
    kind: ClusterProviderConfig
    name: scaleway
