---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-access
spec:
  project: default
  source:
    path: charts/cluster-access
    repoURL: https://github.com/muhlba91/hochschule-burgenland-cluster-applications
    targetRevision: HEAD
    helm:
      releaseName: vcluster-access
      valuesObject:
        gateway:
          enabled: true
          hostname: access.cluster.classroom.hochschule-burgenland.muehlbachler.xyz
          listenerset:
            certificateName: vcluster-access-tls
  destination:
    namespace: vcluster-access
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
