---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.policies.imagePullSecret.name }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "argocd/{{ .Values.policies.imagePullSecret.name }}"
  labels:
    {{- include "bswe-group.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: "{}"
