{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Release.Name }}
  validation:
    wellKnownCACertificates: System
    hostname: {{ .Values.gateway.hostname }}
{{- end }}
