---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bswe-cluster-access
spec:
  project: default
  source:
    path: charts/cluster-access
    repoURL: https://github.com/muhlba91/hochschule-burgenland-cluster-applications
    targetRevision: HEAD
    helm:
      releaseName: bswe-cluster-access
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - host: access.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: bswe-cluster-access-tls
              hosts:
                - access.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz
  destination:
    namespace: bswe-cluster-access
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
