---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bswe-groups
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: demo
            accessGroup1: "dmuehlbachler"
            accessGroup2: ""
  template:
    metadata:
      name: "bswe-group-{{ .name }}-infrastructure"
    spec:
      project: default
      ignoreDifferences:
        - kind: Secret
          name: registry-credentials
          jsonPointers:
            - /data
            - /stringData
      source:
        repoURL: https://github.com/muhlba91/fh-burgenland-bswe-cluster-applications
        path: charts/bswe-group
        targetRevision: HEAD
        helm:
          valuesObject:
            name: "{{ .name }}"
            accessGroup1: "{{ .accessGroup1 }}"
            accessGroup2: "{{ .accessGroup2 }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: bswe-group-{{ .name }}
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - FailOnSharedResource=true
