---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bswe-demo-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: demo
  template:
    metadata:
      name: "cluster-demo-app-group-{{ .name }}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/muhlba91/hochschule-burgenland-cluster-applications
        path: charts/demo-app
        targetRevision: HEAD
        helm:
          releaseName: demo-app
          valuesObject:
            group: "{{ .name }}"
            ingress:
              enabled: true
              hosts:
                - host: "demo.{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: "bswe-group-{{ .name }}-demo-tls"
                  hosts:
                    - "demo.{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
      destination:
        server: "https://cluster-{{ .name }}.cluster-{{ .name }}"
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
