---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bswe-vcluster
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: demo
  template:
    metadata:
      name: "cluster-group-{{ .name }}"
      namespace: argocd
    spec:
      project: default
      ignoreDifferences:
        - kind: Secret
          jsonPointers:
            - /data/CONFIG_READY
            - /data/config.yaml
      source:
        repoURL: https://github.com/muhlba91/hochschule-burgenland-cluster-applications
        path: charts/vcluster
        targetRevision: HEAD
        helm:
          releaseName: "cluster-{{ .name }}"
          valuesObject:
            vcluster:
              controlPlane:
                proxy:
                  extraSANs:
                    - "cluster-{{ .name }}.cluster-{{ .name }}"
                    - "{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
                ingress:
                  host: "{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
                  spec:
                    tls:
                      - hosts:
                          - "{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
                        secretName: "vcluster-{{ .name }}-tls"
              exportKubeConfig:
                server: "https://{{ .name }}.cluster.classroom.bswe.hochschule-burgenland.muehlbachler.xyz"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cluster-{{ .name }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - FailOnSharedResource=true
